# Generated by Django 4.1.1 on 2022-09-08 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('b3aa7316-7e74-4480-8b45-cd5220fd020f'), editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
